import { useState } from "react";

const CALL_PATTERNS = [
  { id: "new_list", label: "新規リスト向け", icon: "📋", desc: "未接触の新規ターゲットへのコールド架電" },
  { id: "exhibition", label: "展示会リード向け", icon: "🏛️", desc: "展示会・セミナーで接触済みのリード" },
  { id: "cold_list", label: "過去名刺・コールドリスト向け", icon: "🗂️", desc: "過去の名刺データや休眠リスト" },
  { id: "web_inquiry", label: "Web問い合わせ向け", icon: "🌐", desc: "Webフォームから問い合わせがあったリード" },
  { id: "upsell", label: "既存顧客アップセル向け", icon: "📈", desc: "既存顧客への追加提案・アップセル" },
];
const DEPARTMENTS = ["経営企画部","総務部","人事部","経理・財務部","情報システム部","営業部","マーケティング部","購買・調達部","製造部","物流部","カスタマーサポート部","法務部","広報部","その他"];
const EMPLOYEE_RANGES = ["1〜10名","11〜30名","31〜50名","51〜100名","101〜300名","301〜500名","501〜1000名","1001名以上"];
const AREA_OPTIONS = ["全国","首都圏（東京・神奈川・埼玉・千葉）","関西圏（大阪・京都・兵庫）","主要都市のみ","東日本","西日本","カスタム指定"];
const INDUSTRIES = ["IT・ソフトウェア","SaaS・クラウド","製造業","建設・不動産","金融・保険","医療・ヘルスケア","小売・EC","物流・運輸","教育・研修","人材・採用","コンサルティング","飲食・ホスピタリティ","メディア・広告","その他"];
const STEPS = [{id:1,label:"サービス情報",icon:"📦"},{id:2,label:"架電パターン",icon:"📞"},{id:3,label:"ターゲット設定",icon:"🎯"},{id:4,label:"営業戦略",icon:"⚡"},{id:5,label:"断り文句",icon:"🛡️"},{id:6,label:"生成・確認",icon:"✨"}];

const C = {
  red:"#e8001d",redDark:"#b50017",redLight:"#fff0f2",gold:"#f5a623",goldLight:"#fff8ed",
  dark:"#0f0f0f",gray:"#2a2a2a",grayLight:"#f5f5f5",white:"#ffffff",
  text:"#1a1a1a",textMuted:"#666",border:"#e8e8e8",
};

function StepIndicator({current}){return(<div style={{display:"flex",alignItems:"center",marginBottom:40}}>{STEPS.map((s,i)=>(<div key={s.id} style={{display:"flex",alignItems:"center",flex:i<STEPS.length-1?1:"none"}}><div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6}}><div style={{width:48,height:48,borderRadius:"50%",background:current===s.id?C.red:current>s.id?C.dark:C.white,border:current===s.id?`2px solid ${C.red}`:current>s.id?`2px solid ${C.dark}`:`2px solid ${C.border}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,color:current>s.id?C.gold:current===s.id?C.white:"#aaa",boxShadow:current===s.id?`0 0 0 4px ${C.redLight},0 4px 12px rgba(232,0,29,0.3)`:"none"}}>{current>s.id?"✓":s.icon}</div><span style={{fontSize:10,fontWeight:700,letterSpacing:"0.05em",whiteSpace:"nowrap",color:current===s.id?C.red:current>s.id?C.dark:"#aaa"}}>{s.label}</span></div>{i<STEPS.length-1&&<div style={{flex:1,height:3,margin:"0 4px",marginBottom:24,background:current>s.id?`linear-gradient(90deg,${C.dark},${C.red})`:"#e8e8e8",borderRadius:2}}/>}</div>))}</div>);}

function MultiSelect({options,selected,onChange,cols=3}){return(<div style={{display:"grid",gridTemplateColumns:`repeat(${cols},1fr)`,gap:8}}>{options.map(o=>{const on=selected.includes(o);return(<button key={o} onClick={()=>onChange(on?selected.filter(x=>x!==o):[...selected,o])} style={{padding:"10px 12px",borderRadius:8,border:`2px solid ${on?C.red:C.border}`,background:on?C.redLight:C.white,color:on?C.red:C.text,fontSize:13,fontWeight:on?700:400,cursor:"pointer",textAlign:"left"}}>{on&&<span style={{marginRight:6}}>✓</span>}{o}</button>);})}</div>);}

const Lbl=({children,req})=>(<div style={{fontSize:13,fontWeight:700,color:C.text,marginBottom:8,display:"flex",alignItems:"center",gap:6}}>{children}{req&&<span style={{background:C.red,color:C.white,fontSize:10,fontWeight:800,padding:"2px 6px",borderRadius:4}}>必須</span>}</div>);

function Inp({value,onChange,placeholder,multi,rows=4}){const s={width:"100%",padding:"12px 16px",borderRadius:10,border:`2px solid ${C.border}`,background:C.white,fontSize:14,color:C.text,outline:"none",fontFamily:"inherit",resize:multi?"vertical":"none",boxSizing:"border-box"};return multi?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={rows} style={s}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={s}/>;}

const Card=({children,style={}})=>(<div style={{background:C.white,borderRadius:16,padding:"32px 36px",border:`1px solid ${C.border}`,boxShadow:"0 4px 24px rgba(0,0,0,0.06)",marginBottom:20,...style}}>{children}</div>);
const H=({children,sub})=>(<div style={{marginBottom:28}}><div style={{fontSize:22,fontWeight:900,color:C.dark,letterSpacing:"-0.02em"}}>{children}</div>{sub&&<div style={{fontSize:13,color:C.textMuted,marginTop:4}}>{sub}</div>}</div>);

function FileUpload({onText}){
  const[name,setName]=useState("");const[loading,setLoading]=useState(false);
  const handle=async(e)=>{const file=e.target.files[0];if(!file)return;setName(file.name);setLoading(true);const reader=new FileReader();reader.onload=async(ev)=>{const base64=ev.target.result.split(",")[1];try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":import.meta.env.VITE_ANTHROPIC_API_KEY,"anthropic-version":"2023-06-01","anthropic-dangerous-allow-browser":"true"},body:JSON.stringify({model:"claude-opus-4-5",max_tokens:2000,messages:[{role:"user",content:[{type:"document",source:{type:"base64",media_type:"application/pdf",data:base64}},{type:"text",text:"このドキュメントの内容を日本語でそのまま抽出してください。"}]}]})});const data=await res.json();onText(data.content?.map(c=>c.text||"").join("")||"");}catch(e){console.error(e);}setLoading(false);};reader.readAsDataURL(file);};
  return(<div style={{marginTop:10}}><label style={{display:"inline-flex",alignItems:"center",gap:8,padding:"9px 18px",borderRadius:8,border:`2px dashed ${C.border}`,background:C.grayLight,cursor:"pointer",fontSize:13,color:C.textMuted,fontWeight:600}}>📎 PDFをアップロード<input type="file" accept="application/pdf" onChange={handle} style={{display:"none"}}/></label>{name&&<span style={{marginLeft:12,fontSize:12,color:loading?C.gold:"#22c55e",fontWeight:700}}>{loading?"📖 読み込み中...":"✓ "+name}</span>}</div>);
}

function ScriptViewer({content}){if(!content)return<div style={{color:"#aaa",fontSize:13,padding:20,textAlign:"center"}}>データがありません</div>;const blocks=content.split(/\n(?=(?:■|STEP\s*\d+|PART|🔑|📋|🏆))/).filter(b=>b.trim());return(<div style={{display:"flex",flexDirection:"column",gap:14}}>{blocks.map((block,i)=>{const lines=block.split("\n").filter(l=>l.trim());const title=lines[0]||"";const accent=/受付|PART\s*1|STEP\s*[AB]|突破/.test(title)?"#2563eb":C.red;return(<div key={i} style={{borderRadius:12,overflow:"hidden",border:`1.5px solid ${accent}22`}}><div style={{background:`linear-gradient(135deg,${accent},${accent}dd)`,padding:"10px 18px",color:C.white,fontWeight:800,fontSize:13}}>{title}</div><div style={{background:C.white,padding:"16px 20px",display:"flex",flexDirection:"column",gap:6}}>{lines.slice(1).map((line,j)=>{if(/💡|ポイント/.test(line))return<div key={j} style={{background:"#fffbeb",border:"1px solid #fde68a",borderRadius:8,padding:"8px 12px",fontSize:12,color:"#92400e",lineHeight:1.7}}>{line}</div>;if(line.includes("→"))return<div key={j} style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:8,padding:"7px 12px",fontSize:13,color:"#166534",lineHeight:1.7}}>{line}</div>;if(/^【.+】/.test(line))return<div key={j} style={{fontSize:12,fontWeight:700,color:"#888",marginTop:4}}>{line}</div>;if(/^\s*[①-⑩]|^\s*\d+\./.test(line))return<div key={j} style={{borderLeft:`3px solid ${accent}`,paddingLeft:10,fontSize:13,color:C.text,lineHeight:1.7}}>{line}</div>;if(/✅|※/.test(line))return<div key={j} style={{background:"#eff6ff",border:"1px solid #bfdbfe",borderRadius:8,padding:"7px 12px",fontSize:12,color:"#1e40af",lineHeight:1.7}}>{line}</div>;return<div key={j} style={{fontSize:13,color:C.text,lineHeight:1.8}}>{line}</div>;})}</div></div>);})}</div>);}

function ObjectionViewer({content}){if(!content)return<div style={{color:"#aaa",fontSize:13,padding:20,textAlign:"center"}}>データがありません</div>;const blocks=content.split(/\n(?=❌)/).filter(b=>b.trim());return(<div style={{display:"flex",flexDirection:"column",gap:14}}>{blocks.map((block,i)=>{const lines=block.split("\n").filter(l=>l.trim());const headline=lines[0].replace("❌","").trim();return(<div key={i} style={{borderRadius:12,overflow:"hidden",border:"1.5px solid #fee2e2"}}><div style={{background:"linear-gradient(135deg,#dc2626,#b91c1c)",padding:"10px 18px",display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:18}}>❌</span><span style={{fontWeight:800,fontSize:13,color:C.white}}>{headline}</span></div><div style={{background:C.white,padding:"14px 18px",display:"flex",flexDirection:"column",gap:8}}>{lines.slice(1).map((line,j)=>{if(line.includes("→"))return<div key={j} style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:8,padding:"8px 12px",fontSize:13,color:"#166534",lineHeight:1.7}}>{line}</div>;if(/^\s*\d+\./.test(line))return<div key={j} style={{fontSize:13,fontWeight:700,color:C.text,paddingTop:4}}>{line}</div>;if(/💡|✅|※/.test(line))return<div key={j} style={{background:"#fffbeb",border:"1px solid #fde68a",borderRadius:8,padding:"7px 12px",fontSize:12,color:"#92400e",lineHeight:1.7}}>{line}</div>;return<div key={j} style={{fontSize:13,color:"#555",lineHeight:1.7}}>{line}</div>;})}</div></div>);})}</div>);}

function FaqViewer({content}){const[open,setOpen]=useState(null);if(!content)return<div style={{color:"#aaa",fontSize:13,padding:20,textAlign:"center"}}>データがありません</div>;const pairs=[];let cur=null;for(const line of content.split("\n")){const t=line.trim();if(!t)continue;if(/^Q[\d\.\s：]+/.test(t)||t.startsWith("Q.")){if(cur)pairs.push(cur);cur={q:t.replace(/^Q[\d\.\s：]+/,"").trim(),a:[]};}else if(/^A[\d\.\s：]+/.test(t)||t.startsWith("A.")){if(cur)cur.a.push(t.replace(/^A[\d\.\s：]+/,"").trim());}else if(cur)cur.a.push(t);}if(cur)pairs.push(cur);return(<div style={{display:"flex",flexDirection:"column",gap:10}}>{pairs.map((p,i)=>(<div key={i} style={{borderRadius:12,border:`1.5px solid ${open===i?C.red:"#e8e8e8"}`,overflow:"hidden"}}><button onClick={()=>setOpen(open===i?null:i)} style={{width:"100%",background:open===i?C.redLight:C.white,padding:"13px 18px",border:"none",cursor:"pointer",display:"flex",alignItems:"flex-start",gap:12,textAlign:"left"}}><span style={{minWidth:26,height:26,borderRadius:"50%",background:open===i?C.red:C.dark,color:C.gold,fontSize:12,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,marginTop:1}}>Q</span><span style={{fontSize:13,fontWeight:700,color:C.text,flex:1,lineHeight:1.6}}>{p.q}</span><span style={{color:C.red,fontSize:14,fontWeight:700}}>{open===i?"▲":"▼"}</span></button>{open===i&&<div style={{padding:"14px 18px 14px 56px",background:C.white,fontSize:13,color:"#374151",lineHeight:1.8,borderTop:`1px solid ${C.redLight}`,whiteSpace:"pre-wrap"}}>{p.a.join("\n")}</div>}</div>))}</div>);}

function VersionHistory({versions,currentId,onRestore}){if(!versions.length)return null;return(<div style={{marginBottom:16}}><div style={{fontSize:12,fontWeight:700,color:C.textMuted,marginBottom:8}}>📁 バージョン履歴</div><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{versions.map((v,i)=>(<button key={v.id} onClick={()=>onRestore(v)} style={{padding:"5px 14px",borderRadius:20,fontSize:12,fontWeight:700,cursor:"pointer",border:`2px solid ${v.id===currentId?C.red:"#ddd"}`,background:v.id===currentId?C.redLight:C.white,color:v.id===currentId?C.red:"#666"}}>v{i+1} — {v.timestamp}</button>))}</div></div>);}

function OutputViewer({output}){const[tab,setTab]=useState("script");const[copied,setCopied]=useState(false);const tabs=[{id:"script",label:"📝 トークスクリプト"},{id:"objection",label:"🛡️ 切り返しトーク"},{id:"faq",label:"❓ FAQ"}];const copyAll=()=>{navigator.clipboard.writeText([output.talkScript,output.objectionHandling,output.faq].join("\n\n"+"=".repeat(50)+"\n\n"));setCopied(true);setTimeout(()=>setCopied(false),2000);};return(<div style={{background:C.white,borderRadius:16,border:`1px solid ${C.border}`,overflow:"hidden",boxShadow:"0 4px 24px rgba(0,0,0,0.08)"}}><div style={{display:"flex",borderBottom:`2px solid ${C.grayLight}`,background:C.white,padding:"0 20px"}}>{tabs.map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} style={{padding:"14px 16px",border:"none",cursor:"pointer",background:"transparent",fontWeight:tab===t.id?800:500,fontSize:13,color:tab===t.id?C.red:"#888",borderBottom:tab===t.id?`3px solid ${C.red}`:"3px solid transparent",marginBottom:-2,whiteSpace:"nowrap"}}>{t.label}</button>))}<button onClick={copyAll} style={{marginLeft:"auto",padding:"6px 16px",borderRadius:8,border:`2px solid ${copied?"#22c55e":C.border}`,background:copied?"#f0fdf4":C.white,color:copied?"#22c55e":C.textMuted,fontSize:11,fontWeight:700,cursor:"pointer",alignSelf:"center"}}>{copied?"✓ コピー済み":"📋 全コピー"}</button></div><div style={{padding:"24px 20px",background:C.grayLight,minHeight:300,maxHeight:620,overflowY:"auto"}}>{tab==="script"&&<ScriptViewer content={output.talkScript}/>}{tab==="objection"&&<ObjectionViewer content={output.objectionHandling}/>}{tab==="faq"&&<FaqViewer content={output.faq}/>}</div></div>);}

export default function CanviTool(){
  const[step,setStep]=useState(1);const[loading,setLoading]=useState(false);const[versions,setVersions]=useState([]);const[currentId,setCurrentId]=useState(null);const[feedback,setFeedback]=useState("");const[output,setOutput]=useState(null);
  const[form,setForm]=useState({companyName:"",serviceName:"",serviceOverview:"",serviceUrl:"",talkScript:"",voiceNote:"",callPattern:"",industries:[],employeeRange:[],departments:[],area:"",contactRole:"",goal:"",appealPoints:"",differentiation:"",competitors:"",rcptObjections:"",contactObjections:"",situationNotes:""});
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const canNext=()=>{if(step===1)return form.companyName&&form.serviceName&&form.serviceOverview;if(step===2)return form.callPattern;if(step===3)return form.industries.length>0&&form.area;if(step===4)return form.appealPoints;return true;};
  const buildPrompt=(fb="")=>{const p=CALL_PATTERNS.find(x=>x.id===form.callPattern);return`あなたはThe Model型テレアポのトップエキスパートです。以下の情報をもとにアポインターが実際に使えるトーク素材を作成してください。\n\n会社名:${form.companyName} / サービス名:${form.serviceName}\n概要:${form.serviceOverview}\nURL:${form.serviceUrl||"なし"} / 既存スクリプト参考:${form.talkScript||"なし"}\n架電パターン:${p?.label}（${p?.desc}）\n業界:${form.industries.join("、")} / 従業員数:${form.employeeRange.join("、")||"指定なし"}\n担当部署:${form.departments.join("、")||"指定なし"} / エリア:${form.area} / 役職:${form.contactRole||"指定なし"}\n目標:${form.goal||"アポイント獲得"} / 訴求:${form.appealPoints}\n差別化:${form.differentiation||"なし"} / 競合:${form.competitors||"なし"}\n受付断り:${form.rcptObjections||"なし"} / 担当者断り:${form.contactObjections||"なし"}\nその他:${form.situationNotes||"なし"}\n${fb?`修正指示:${fb}`:""}\n\n出力はJSON形式のみ。前置き・後書き不要。\n\ntalkScript構成:\n■ PART1 受付突破（ナチュラル型）\nSTEP A: 最初の一言（具体セリフ＋💡ポイント）\nSTEP B: 受付の返答パターン別3〜5パターン（各:❌パターン名→具体セリフ→💡ポイント）\n🏆 ゴールデンルール（箇条書き）\n■ PART2 担当者トーク\nSTEP 02 [HOOK] / STEP 03 [PAIN] / STEP 04 [VALUE] / STEP 05 [CLOSE] / STEP 06 [CONFIRM]（各STEP: 具体的セリフ＋💡ポイント）\n\nobjectionHandling構成:受付用5個＋担当者用5個、計10個。各: ❌「断り文句」の見出し＋1.共感→セリフ 2.転換→セリフ 3.クロージング→セリフ\n\nfaq構成: Q1〜Q10の10個\n\n{"talkScript":"...","objectionHandling":"...","faq":"..."}`;};
  const generate=async(fb="")=>{setLoading(true);try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":import.meta.env.VITE_ANTHROPIC_API_KEY,"anthropic-version":"2023-06-01","anthropic-dangerous-allow-browser":"true"},body:JSON.stringify({model:"claude-opus-4-5",max_tokens:4000,messages:[{role:"user",content:buildPrompt(fb)}]})});const data=await res.json();const text=data.content?.map(c=>c.text||"").join("")||"";let parsed;try{parsed=JSON.parse(text.replace(/```json|```/g,"").trim());}catch{parsed={talkScript:text,objectionHandling:"",faq:""};}const ver={id:Date.now(),timestamp:new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"}),data:parsed};setVersions(v=>[...v,ver]);setCurrentId(ver.id);setOutput(parsed);setFeedback("");}catch(e){console.error(e);alert("生成に失敗しました。APIキーを確認してください。");}setLoading(false);};
  const downloadTxt=()=>{if(!output)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([[output.talkScript,output.objectionHandling,output.faq].join("\n\n"+"=".repeat(60)+"\n\n")],{type:"text/plain;charset=utf-8"}));a.download=`${form.serviceName||"teleapo"}_スクリプト_v${versions.length}.txt`;a.click();};

  return(
    <div style={{minHeight:"100vh",background:"#f7f7f7",fontFamily:"'Hiragino Kaku Gothic ProN','Yu Gothic',sans-serif",paddingBottom:80}}>

      {/* ヘッダー */}
      <div style={{background:C.dark,padding:"0 32px",display:"flex",alignItems:"center",justifyContent:"space-between",height:52,boxShadow:"0 2px 16px rgba(0,0,0,0.4)",position:"sticky",top:0,zIndex:100,borderBottom:`2px solid ${C.red}`}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <span style={{fontSize:20}}>📞</span>
          <div>
            <span style={{color:C.white,fontWeight:900,fontSize:16,letterSpacing:"0.05em"}}>テレアポの達人</span>
            <span style={{color:C.gold,fontSize:10,fontWeight:700,letterSpacing:"0.1em",marginLeft:8}}>AI SCRIPT GENERATOR</span>
          </div>
        </div>
        <div style={{color:"#666",fontSize:12,fontWeight:600}}>by 株式会社Canvi</div>
      </div>

      {/* ヒーローバナー（スリム版） */}
      <div style={{background:`linear-gradient(135deg,${C.dark} 0%,#1a0005 100%)`,padding:"20px 40px",borderBottom:`3px solid ${C.red}`}}>
        <div style={{maxWidth:860,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"space-between"}}>
          <div>
            <div style={{fontSize:11,fontWeight:700,color:C.red,letterSpacing:"0.15em",marginBottom:4}}>🔥 AI POWERED TELEAPO TOOL</div>
            <div style={{fontSize:20,fontWeight:900,color:C.white,lineHeight:1.3}}>
              最強のトークスクリプトを、<span style={{color:C.gold}}>AIが瞬時に設計する。</span>
            </div>
          </div>
          <div style={{display:"flex",gap:16,color:"#555",fontSize:11,fontWeight:600"}}>
            <span>STEP 1-6で簡単入力</span>
            <span>→</span>
            <span>AIが自動生成</span>
            <span>→</span>
            <span>即使えるスクリプト</span>
          </div>
        </div>
      </div>

      <div style={{maxWidth:860,margin:"0 auto",padding:"36px 24px 0"}}>
        <StepIndicator current={step}/>

        {step===1&&(<Card><H sub="クライアントのサービス情報を入力してください">📦 サービス基本情報</H><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,marginBottom:20}}><div><Lbl req>クライアント会社名</Lbl><Inp value={form.companyName} onChange={v=>set("companyName",v)} placeholder="例：株式会社〇〇"/></div><div><Lbl req>サービス名</Lbl><Inp value={form.serviceName} onChange={v=>set("serviceName",v)} placeholder="例：〇〇クラウド"/></div></div><div style={{marginBottom:20}}><Lbl req>サービス概要</Lbl><div style={{background:C.goldLight,border:`1px solid ${C.gold}44`,borderRadius:8,padding:"10px 14px",fontSize:12,color:"#92400e",marginBottom:10,fontWeight:600}}>💡 テキストで入力 または PDFをアップロード（どちらか必須）</div><Inp value={form.serviceOverview} onChange={v=>set("serviceOverview",v)} placeholder="サービスの特徴・解決できる課題・実績などを入力" multi rows={4}/><FileUpload onText={t=>set("serviceOverview",t)}/></div><div style={{marginBottom:20}}><Lbl>サービスURL（任意）</Lbl><Inp value={form.serviceUrl} onChange={v=>set("serviceUrl",v)} placeholder="https://..."/></div><div style={{marginBottom:20}}><Lbl>既存トークスクリプト（任意）</Lbl><Inp value={form.talkScript} onChange={v=>set("talkScript",v)} placeholder="既存スクリプトがあれば貼り付けてください" multi rows={4}/><FileUpload onText={t=>set("talkScript",t)}/></div><div><Lbl>音声データの文字起こし（任意）</Lbl><Inp value={form.voiceNote} onChange={v=>set("voiceNote",v)} placeholder="音声データを文字起こしして貼り付けてください" multi rows={3}/></div></Card>)}

        {step===2&&(<Card><H sub="架電の目的・状況に合ったパターンを選んでください">📞 架電パターン選択</H><div style={{display:"flex",flexDirection:"column",gap:12}}>{CALL_PATTERNS.map(p=>(<button key={p.id} onClick={()=>set("callPattern",p.id)} style={{padding:"18px 22px",borderRadius:12,border:`2px solid ${form.callPattern===p.id?C.red:C.border}`,background:form.callPattern===p.id?C.redLight:C.white,cursor:"pointer",textAlign:"left",display:"flex",alignItems:"center",gap:16,boxShadow:form.callPattern===p.id?`0 4px 16px rgba(232,0,29,0.15)`:"none"}}><span style={{fontSize:30}}>{p.icon}</span><div style={{flex:1}}><div style={{fontWeight:800,fontSize:15,color:form.callPattern===p.id?C.red:C.text}}>{p.label}</div><div style={{fontSize:12,color:C.textMuted,marginTop:3}}>{p.desc}</div></div>{form.callPattern===p.id&&<div style={{width:28,height:28,borderRadius:"50%",background:C.red,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontWeight:900,fontSize:14}}>✓</div>}</button>))}</div></Card>)}

        {step===3&&(<Card><H sub="架電するターゲットの条件を設定してください">🎯 ターゲット設定</H><div style={{marginBottom:24}}><Lbl req>業界（複数選択可）</Lbl><MultiSelect options={INDUSTRIES} selected={form.industries} onChange={v=>set("industries",v)} cols={4}/></div><div style={{marginBottom:24}}><Lbl>従業員数（複数選択可）</Lbl><MultiSelect options={EMPLOYEE_RANGES} selected={form.employeeRange} onChange={v=>set("employeeRange",v)} cols={4}/></div><div style={{marginBottom:24}}><Lbl>担当部署（複数選択可）</Lbl><MultiSelect options={DEPARTMENTS} selected={form.departments} onChange={v=>set("departments",v)} cols={4}/></div><div style={{marginBottom:24}}><Lbl req>エリア</Lbl><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{AREA_OPTIONS.map(a=>(<button key={a} onClick={()=>set("area",a)} style={{padding:"9px 18px",borderRadius:20,border:`2px solid ${form.area===a?C.red:C.border}`,background:form.area===a?C.redLight:C.white,color:form.area===a?C.red:C.text,fontSize:13,fontWeight:form.area===a?700:400,cursor:"pointer"}}>{form.area===a&&"✓ "}{a}</button>))}</div></div><div><Lbl>担当者役職（任意）</Lbl><Inp value={form.contactRole} onChange={v=>set("contactRole",v)} placeholder="例：部長クラス、IT担当者、経営者"/></div></Card>)}

        {step===4&&(<Card><H sub="勝てる営業戦略の核心を入力してください">⚡ 営業戦略</H><div style={{marginBottom:20}}><Lbl>架電目標・KPI</Lbl><Inp value={form.goal} onChange={v=>set("goal",v)} placeholder="例：1時間のオンライン商談アポ獲得"/></div><div style={{marginBottom:20}}><Lbl req>主な訴求ポイント・強み</Lbl><Inp value={form.appealPoints} onChange={v=>set("appealPoints",v)} placeholder="例：導入実績500社、コスト30%削減、初月無料トライアル可能" multi rows={4}/></div><div style={{marginBottom:20}}><Lbl>競合との差別化ポイント</Lbl><Inp value={form.differentiation} onChange={v=>set("differentiation",v)} placeholder="例：API連携が業界最多、24時間サポート" multi rows={3}/></div><div><Lbl>主な競合（任意）</Lbl><Inp value={form.competitors} onChange={v=>set("competitors",v)} placeholder="例：Salesforce、HubSpot、kintone"/></div></Card>)}

        {step===5&&(<Card><H sub="よくある断り文句を入力すると切り返しトークの精度が上がります">🛡️ 断り文句・想定状況</H><div style={{background:C.goldLight,border:`1px solid ${C.gold}44`,borderRadius:10,padding:"12px 16px",marginBottom:24,fontSize:13,color:"#92400e",fontWeight:600}}>💡 受付突破トークと担当者トーク、それぞれの切り返しを生成します。</div><div style={{marginBottom:24}}><Lbl>受付での断り文句</Lbl><Inp value={form.rcptObjections} onChange={v=>set("rcptObjections",v)} placeholder='例：「担当者不在」「折り返し不可」「資料送って」' multi rows={4}/></div><div style={{marginBottom:24}}><Lbl>担当者からの断り文句</Lbl><Inp value={form.contactObjections} onChange={v=>set("contactObjections",v)} placeholder='例：「予算がない」「他社使ってる」「忙しい」' multi rows={4}/></div><div><Lbl>その他・特記事項</Lbl><Inp value={form.situationNotes} onChange={v=>set("situationNotes",v)} placeholder="例：競合が強い業界、規制がある" multi rows={3}/></div></Card>)}

        {step===6&&(<div>{!output&&!loading&&(<Card><H sub="入力内容をもとにAIがトーク素材を設計します">✨ 生成準備完了</H><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:28}}>{[["📝 PART1","受付突破トーク（パターン別+ゴールデンルール）"],["📝 PART2","担当者トーク（HOOK→PAIN→VALUE→CLOSE→CONFIRM）"],["🛡️ PART3","切り返しトーク10選（受付5個+担当者5個）"],["❓ PART4","FAQ 10選"]].map(([icon,desc],i)=>(<div key={i} style={{background:C.grayLight,borderRadius:10,padding:"14px 16px",border:`1px solid ${C.border}`}}><div style={{fontWeight:800,fontSize:13,color:C.dark,marginBottom:4}}>{icon}</div><div style={{fontSize:12,color:C.textMuted}}>{desc}</div></div>))}</div><button onClick={()=>generate()} style={{width:"100%",padding:"18px",borderRadius:12,background:`linear-gradient(135deg,${C.red},${C.redDark})`,color:C.white,fontWeight:900,fontSize:17,border:"none",cursor:"pointer",boxShadow:`0 6px 24px rgba(232,0,29,0.35)`,letterSpacing:"0.05em"}}>🚀 トーク素材を生成する</button></Card>)}{loading&&(<Card style={{textAlign:"center",padding:"70px 32px"}}><div style={{fontSize:50,marginBottom:16}}>⚡</div><div style={{fontSize:18,fontWeight:900,color:C.dark,marginBottom:8}}>AIが設計中...</div><div style={{fontSize:13,color:C.textMuted}}>最強のトーク素材を生成しています（30秒程度）</div></Card>)}{output&&!loading&&(<div><VersionHistory versions={versions} currentId={currentId} onRestore={v=>{setOutput(v.data);setCurrentId(v.id);}}/><OutputViewer output={output}/><Card style={{background:C.grayLight,marginTop:16}}><div style={{fontSize:14,fontWeight:800,color:C.dark,marginBottom:12}}>🔄 フィードバック・ブラッシュアップ</div><Inp value={feedback} onChange={setFeedback} placeholder='例：「切り返しをより共感的に」「FAQに価格の質問を追加」' multi rows={3}/><button onClick={()=>generate(feedback)} disabled={!feedback} style={{marginTop:12,padding:"11px 28px",borderRadius:10,background:feedback?C.dark:"#ddd",color:C.white,fontWeight:700,fontSize:14,border:"none",cursor:feedback?"pointer":"not-allowed"}}>再生成する</button></Card><div style={{display:"flex",gap:12,marginTop:12}}><button onClick={downloadTxt} style={{flex:1,padding:"15px",borderRadius:12,background:`linear-gradient(135deg,${C.red},${C.redDark})`,color:C.white,fontWeight:800,fontSize:14,border:"none",cursor:"pointer",boxShadow:`0 4px 16px rgba(232,0,29,0.25)`}}>📥 テキストでダウンロード</button><button onClick={()=>window.print()} style={{flex:1,padding:"15px",borderRadius:12,background:C.dark,color:C.white,fontWeight:800,fontSize:14,border:"none",cursor:"pointer"}}>🖨️ 印刷 / PDF保存</button></div></div>)}</div>)}

        <div style={{display:"flex",justifyContent:"space-between",marginTop:28}}>
          {step>1&&<button onClick={()=>setStep(s=>s-1)} style={{padding:"13px 30px",borderRadius:10,border:`2px solid ${C.border}`,background:C.white,color:C.text,fontWeight:700,fontSize:14,cursor:"pointer"}}>← 戻る</button>}
          {step<6&&<button onClick={()=>setStep(s=>s+1)} disabled={!canNext()} style={{padding:"13px 36px",borderRadius:10,border:"none",background:canNext()?`linear-gradient(135deg,${C.red},${C.redDark})`:"#ddd",color:C.white,fontWeight:800,fontSize:14,cursor:canNext()?"pointer":"not-allowed",marginLeft:"auto",boxShadow:canNext()?`0 4px 16px rgba(232,0,29,0.25)`:"none"}}>次へ →</button>}
        </div>
      </div>
    </div>
  );
}
